frutas = ("manzana", "pera", "naranja", "papaya")
colores = ("azul", "amarillo", "violeta", "gris")
print("lista de frutas:", frutas)
print("lista de colores:",colores)
print("lista de frutas:", frutas)
frutas.append("guanabana")
print("lista de frutas:", frutas)
frutas.append("higo")
print("lista de frutas:", frutas)
frutas.remove("pera")
print("listas de frutas:", frutas)
frutas.pop(3)
print("lista de frutascon la 3 eliminada", frutas)
frutas[3]="guayaba"
print("cambio de guanabana por guayaba")
